After cleaning the datasets:

Generate Summary Statistics

For numerical columns:

- Mean
- Median
- Minimum
- Maximum
- Standard Deviation

Explore Data Patterns

Perform at least 5 exploratory analyses for each dataset.

Examples include:

E-commerce Dataset

- Top-selling products
- Highest revenue-generating countries
- Monthly sales trends
- Most purchased products
- Customer purchasing behavior

In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv(r"C:\Users\IT\Desktop\Data Analysis\AnalystLab Africa Internship\OnlineRetail.csv\cleaned_online_retail.csv",low_memory=False)
df

,invoiceno,stockcode,description,quantity,invoicedate,unitprice,customerid,country
0,536365,85123A,White Hanging Heart T-Light Holder,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,White Metal Lantern,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,Cream Cupid Hearts Coat Hanger,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,Knitted Union Flag Hot Water Bottle,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,Red Woolly Hottie White Heart.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
524873,581587,22613,Pack Of 20 Spaceboy Napkins,12,2011-12-09 12:50:00,0.85,12680.0,France
524874,581587,22899,Children'S Apron Dolly Girl,6,2011-12-09 12:50:00,2.10,12680.0,France
524875,581587,23254,Childrens Cutlery Dolly Girl,4,2011-12-09 12:50:00,4.15,12680.0,France
524876,581587,23255,Childrens Cutlery Circus Parade,4,2011-12-09 12:50:00,4.15,12680.0,France
524877,581587,22138,Baking Set 9 Piece Retrospot,3,2011-12-09 12:50:00,4.95,12680.0,France

In [5]:
# Create Revenue Column
df['revenue']=df['quantity']*df['unitprice']
df['revenue']

0         15.30
1         20.34
2         22.00
3         20.34
4         20.34
          ...
524873    10.20
524874    12.60
524875    16.60
524876    16.60
524877    14.85
Name: revenue, Length: 524878, dtype: float64

In [6]:
df.describe()

            quantity      unitprice     customerid        revenue
count  524878.000000  524878.000000  524878.000000  524878.000000
mean       10.616600       3.922573   15930.834230      20.275399
std       156.280031      36.093028    1850.669004     271.693566
min         1.000000       0.001000   12346.000000       0.001000
25%         1.000000       1.250000   14375.000000       3.900000
50%         4.000000       2.080000   16265.000000       9.920000
75%        11.000000       4.130000   17841.000000      17.700000
max     80995.000000   13541.330000   18287.000000  168469.600000

In [7]:
# Top selling products
top_products=df.groupby('description')['quantity'].sum().sort_values(ascending=False).head(10)

top_products

description
Paper Craft , Little Birdie           80995
Medium Ceramic Top Storage Jar        78033
World War 2 Gliders Asstd Designs     54951
Jumbo Bag Red Retrospot               48371
White Hanging Heart T-Light Holder    37872
Popcorn Holder                        36749
Pack Of 72 Retrospot Cake Cases       36396
Assorted Colour Bird Ornament         36362
Rabbit Night Light                    30739
Mini Paint Set Vintage                26633
Name: quantity, dtype: int64

In [8]:
# Highest Revenue Country
country_rev=df.groupby('country')['revenue'].sum().sort_values(ascending=False)

country_rev.head(10)

country
United Kingdom    9001744.094
Netherlands        285446.340
Eire               283140.520
Germany            228678.400
France             209625.370
Australia          138453.810
Spain               61558.560
Switzerland         57067.600
Belgium             41196.340
Sweden              38367.830
Name: revenue, dtype: float64

In [13]:
df['invoicedate'].dtype

In [14]:
df['invoicedate'] = pd.to_datetime(df['invoicedate'])

In [15]:
df['invoicedate'].dtype

dtype('<M8[us]')

In [16]:
#Monthly sales Trend
df['month']=df['invoicedate'].dt.to_period('M')

monthly_sales=df.groupby('month')['revenue'].sum()

monthly_sales

month
2010-12     821452.730
2011-01     689811.610
2011-02     522545.560
2011-03     716215.260
2011-04     536968.491
2011-05     769296.610
2011-06     760547.010
2011-07     718076.121
2011-08     757841.380
2011-09    1056435.192
2011-10    1151263.730
2011-11    1503866.780
2011-12     637790.330
Freq: M, Name: revenue, dtype: float64

In [17]:
# Most purchased product
df['description'].value_counts().head(10)

description
White Hanging Heart T-Light Holder    2311
Jumbo Bag Red Retrospot               2109
Regency Cakestand 3 Tier              2007
Party Bunting                         1699
Lunch Bag Red Retrospot               1581
Assorted Colour Bird Ornament         1476
Set Of 3 Cake Tins Pantry Design      1392
Pack Of 72 Retrospot Cake Cases       1352
Lunch Bag  Black Skull.               1301
Natural Slate Heart Chalkboard        1255
Name: count, dtype: int64

In [18]:
# Customer purchased behavior
customer_purchase=df.groupby('customerid')['revenue'].sum()

customer_purchase.describe()

count    4.338000e+03
mean     2.453230e+03
std      2.866704e+04
min      3.750000e+00
25%      3.064825e+02
50%      6.685700e+02
75%      1.660597e+03
max      1.795422e+06
Name: revenue, dtype: float64